master:
  push:
    - imports: https://cnb.cool/motorao/secrets/-/blob/main/envs.yml
      stages:
        - name: Build Jekyll site
          image: ruby:3.3
          script: |
            gem install bundler
            bundle install
            bundle exec jekyll build
        - name: Deploy to EdgeOne Makers
          image: node:20
          script: npx edgeone makers deploy _site -n motoraocn -t $EDGEONE_API_TOKEN
        - name: Bark 发布成功通知
          image: node:20
          script: curl -s "https://api.day.app/PWhxDvCuLGMofA5cr8YuaY/EdgeOne%E5%8F%91%E5%B8%83%E6%88%90%E5%8A%9F?url=https://blog.motorao.cn"
