markdown: kramdown
permalink: /:title/
url: https://89ao.github.io
name: MotorAo
author: motorao
#qq: xx
email: 89ao@live.com
#duoshuo: 89ao
beian: 苏ICP备2022047997号-1 
#cnzz: 119959
#weibo: 2067815867
#gitcafe: 89ao
github: 89ao
highlighter: rouge
safe: true
paginate: 20
about: "攻城狮一头，PM狗（P for project）,云计算从业9年。	
热爱Linux，开源爱好者，爱好胶片摄影，户外运动。		
OS洁癖与性能压榨狂魔。  	
偶尔微博，偶尔wow。"
plugins: [jekyll-paginate]
defaults:
 -
  scope:
    path: "_posts" # 一个空的字符串代表项目中所有的文件
  values:
    layout: "post"
    author: "motorao"
